// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module krnl_helm_dataflow_in_loop_VITIS_LOOP_112_1 (
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        in_r,
        count,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RFIFONUM,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        out_r,
        ap_clk,
        ap_rst,
        out_r_ap_vld,
        ap_start,
        in_r_ap_vld,
        count_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);


output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [63:0] m_axi_gmem0_WDATA;
output  [7:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [63:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [8:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [63:0] in_r;
input  [31:0] count;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [63:0] m_axi_gmem1_WDATA;
output  [7:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [63:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [8:0] m_axi_gmem1_RFIFONUM;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
input  [63:0] out_r;
input   ap_clk;
input   ap_rst;
input   out_r_ap_vld;
input   ap_start;
input   in_r_ap_vld;
input   count_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_out_r_c_din;
wire    entry_proc_U0_out_r_c_write;
wire    entry_proc_U0_ap_ext_blocking_n;
wire    entry_proc_U0_ap_str_blocking_n;
wire    entry_proc_U0_ap_int_blocking_n;
wire    read_data_1_U0_ap_start;
wire    read_data_1_U0_ap_done;
wire    read_data_1_U0_ap_continue;
wire    read_data_1_U0_ap_idle;
wire    read_data_1_U0_ap_ready;
wire    read_data_1_U0_start_out;
wire    read_data_1_U0_start_write;
wire    read_data_1_U0_m_axi_gmem0_AWVALID;
wire   [63:0] read_data_1_U0_m_axi_gmem0_AWADDR;
wire   [0:0] read_data_1_U0_m_axi_gmem0_AWID;
wire   [31:0] read_data_1_U0_m_axi_gmem0_AWLEN;
wire   [2:0] read_data_1_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] read_data_1_U0_m_axi_gmem0_AWBURST;
wire   [1:0] read_data_1_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] read_data_1_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] read_data_1_U0_m_axi_gmem0_AWPROT;
wire   [3:0] read_data_1_U0_m_axi_gmem0_AWQOS;
wire   [3:0] read_data_1_U0_m_axi_gmem0_AWREGION;
wire   [0:0] read_data_1_U0_m_axi_gmem0_AWUSER;
wire    read_data_1_U0_m_axi_gmem0_WVALID;
wire   [63:0] read_data_1_U0_m_axi_gmem0_WDATA;
wire   [7:0] read_data_1_U0_m_axi_gmem0_WSTRB;
wire    read_data_1_U0_m_axi_gmem0_WLAST;
wire   [0:0] read_data_1_U0_m_axi_gmem0_WID;
wire   [0:0] read_data_1_U0_m_axi_gmem0_WUSER;
wire    read_data_1_U0_m_axi_gmem0_ARVALID;
wire   [63:0] read_data_1_U0_m_axi_gmem0_ARADDR;
wire   [0:0] read_data_1_U0_m_axi_gmem0_ARID;
wire   [31:0] read_data_1_U0_m_axi_gmem0_ARLEN;
wire   [2:0] read_data_1_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] read_data_1_U0_m_axi_gmem0_ARBURST;
wire   [1:0] read_data_1_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] read_data_1_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] read_data_1_U0_m_axi_gmem0_ARPROT;
wire   [3:0] read_data_1_U0_m_axi_gmem0_ARQOS;
wire   [3:0] read_data_1_U0_m_axi_gmem0_ARREGION;
wire   [0:0] read_data_1_U0_m_axi_gmem0_ARUSER;
wire    read_data_1_U0_m_axi_gmem0_RREADY;
wire    read_data_1_U0_m_axi_gmem0_BREADY;
wire   [63:0] read_data_1_U0_S0_buf4_din;
wire    read_data_1_U0_S0_buf4_write;
wire   [63:0] read_data_1_U0_D0_buf5_din;
wire    read_data_1_U0_D0_buf5_write;
wire   [63:0] read_data_1_U0_u0_buf6_din;
wire    read_data_1_U0_u0_buf6_write;
wire   [31:0] read_data_1_U0_count_c_din;
wire    read_data_1_U0_count_c_write;
wire    read_data_1_U0_ap_ext_blocking_n;
wire    read_data_1_U0_ap_str_blocking_n;
wire    read_data_1_U0_ap_int_blocking_n;
wire    compute_1_U0_ap_start;
wire    compute_1_U0_ap_done;
wire    compute_1_U0_ap_continue;
wire    compute_1_U0_ap_idle;
wire    compute_1_U0_ap_ready;
wire    compute_1_U0_S0_buf4_read;
wire    compute_1_U0_D0_buf5_read;
wire    compute_1_U0_u0_buf6_read;
wire   [63:0] compute_1_U0_v0_buf7_din;
wire    compute_1_U0_v0_buf7_write;
wire    compute_1_U0_ap_ext_blocking_n;
wire    compute_1_U0_ap_str_blocking_n;
wire    compute_1_U0_ap_int_blocking_n;
wire    write_data_1_U0_ap_start;
wire    write_data_1_U0_ap_done;
wire    write_data_1_U0_ap_continue;
wire    write_data_1_U0_ap_idle;
wire    write_data_1_U0_ap_ready;
wire    write_data_1_U0_m_axi_gmem1_AWVALID;
wire   [63:0] write_data_1_U0_m_axi_gmem1_AWADDR;
wire   [0:0] write_data_1_U0_m_axi_gmem1_AWID;
wire   [31:0] write_data_1_U0_m_axi_gmem1_AWLEN;
wire   [2:0] write_data_1_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] write_data_1_U0_m_axi_gmem1_AWBURST;
wire   [1:0] write_data_1_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] write_data_1_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] write_data_1_U0_m_axi_gmem1_AWPROT;
wire   [3:0] write_data_1_U0_m_axi_gmem1_AWQOS;
wire   [3:0] write_data_1_U0_m_axi_gmem1_AWREGION;
wire   [0:0] write_data_1_U0_m_axi_gmem1_AWUSER;
wire    write_data_1_U0_m_axi_gmem1_WVALID;
wire   [63:0] write_data_1_U0_m_axi_gmem1_WDATA;
wire   [7:0] write_data_1_U0_m_axi_gmem1_WSTRB;
wire    write_data_1_U0_m_axi_gmem1_WLAST;
wire   [0:0] write_data_1_U0_m_axi_gmem1_WID;
wire   [0:0] write_data_1_U0_m_axi_gmem1_WUSER;
wire    write_data_1_U0_m_axi_gmem1_ARVALID;
wire   [63:0] write_data_1_U0_m_axi_gmem1_ARADDR;
wire   [0:0] write_data_1_U0_m_axi_gmem1_ARID;
wire   [31:0] write_data_1_U0_m_axi_gmem1_ARLEN;
wire   [2:0] write_data_1_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] write_data_1_U0_m_axi_gmem1_ARBURST;
wire   [1:0] write_data_1_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] write_data_1_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] write_data_1_U0_m_axi_gmem1_ARPROT;
wire   [3:0] write_data_1_U0_m_axi_gmem1_ARQOS;
wire   [3:0] write_data_1_U0_m_axi_gmem1_ARREGION;
wire   [0:0] write_data_1_U0_m_axi_gmem1_ARUSER;
wire    write_data_1_U0_m_axi_gmem1_RREADY;
wire    write_data_1_U0_m_axi_gmem1_BREADY;
wire    write_data_1_U0_out_r_read;
wire    write_data_1_U0_v0_buf7_read;
wire    write_data_1_U0_count_read;
wire    write_data_1_U0_ap_ext_blocking_n;
wire    write_data_1_U0_ap_str_blocking_n;
wire    write_data_1_U0_ap_int_blocking_n;
wire    out_r_c_full_n;
wire   [63:0] out_r_c_dout;
wire   [2:0] out_r_c_num_data_valid;
wire   [2:0] out_r_c_fifo_cap;
wire    out_r_c_empty_n;
wire    S0_buf_full_n;
wire   [63:0] S0_buf_dout;
wire   [7:0] S0_buf_num_data_valid;
wire   [7:0] S0_buf_fifo_cap;
wire    S0_buf_empty_n;
wire    D0_buf_full_n;
wire   [63:0] D0_buf_dout;
wire   [11:0] D0_buf_num_data_valid;
wire   [11:0] D0_buf_fifo_cap;
wire    D0_buf_empty_n;
wire    u0_buf_full_n;
wire   [63:0] u0_buf_dout;
wire   [11:0] u0_buf_num_data_valid;
wire   [11:0] u0_buf_fifo_cap;
wire    u0_buf_empty_n;
wire    count_c_full_n;
wire   [31:0] count_c_dout;
wire   [2:0] count_c_num_data_valid;
wire   [2:0] count_c_fifo_cap;
wire    count_c_empty_n;
wire    v0_buf_full_n;
wire   [63:0] v0_buf_dout;
wire   [11:0] v0_buf_num_data_valid;
wire   [11:0] v0_buf_fifo_cap;
wire    v0_buf_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_read_data_1_U0_ap_ready;
wire    ap_sync_read_data_1_U0_ap_ready;
wire   [0:0] start_for_write_data_1_U0_din;
wire    start_for_write_data_1_U0_full_n;
wire   [0:0] start_for_write_data_1_U0_dout;
wire    start_for_write_data_1_U0_empty_n;
wire   [0:0] start_for_compute_1_U0_din;
wire    start_for_compute_1_U0_full_n;
wire   [0:0] start_for_compute_1_U0_dout;
wire    start_for_compute_1_U0_empty_n;
wire    ap_ext_blocking_cur_n;
wire    ap_str_blocking_cur_n;
wire    ap_int_blocking_cur_n;
wire    ap_ext_blocking_sub_n;
wire    ap_str_blocking_sub_n;
wire    ap_int_blocking_sub_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read_data_1_U0_ap_ready = 1'b0;
end

krnl_helm_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_write_data_1_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .out_r(out_r),
    .out_r_c_din(entry_proc_U0_out_r_c_din),
    .out_r_c_num_data_valid(out_r_c_num_data_valid),
    .out_r_c_fifo_cap(out_r_c_fifo_cap),
    .out_r_c_full_n(out_r_c_full_n),
    .out_r_c_write(entry_proc_U0_out_r_c_write),
    .ap_ext_blocking_n(entry_proc_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(entry_proc_U0_ap_str_blocking_n),
    .ap_int_blocking_n(entry_proc_U0_ap_int_blocking_n)
);

krnl_helm_read_data_1 read_data_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(read_data_1_U0_ap_start),
    .start_full_n(start_for_compute_1_U0_full_n),
    .ap_done(read_data_1_U0_ap_done),
    .ap_continue(read_data_1_U0_ap_continue),
    .ap_idle(read_data_1_U0_ap_idle),
    .ap_ready(read_data_1_U0_ap_ready),
    .start_out(read_data_1_U0_start_out),
    .start_write(read_data_1_U0_start_write),
    .m_axi_gmem0_AWVALID(read_data_1_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(read_data_1_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(read_data_1_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(read_data_1_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(read_data_1_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(read_data_1_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(read_data_1_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(read_data_1_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(read_data_1_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(read_data_1_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(read_data_1_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(read_data_1_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(read_data_1_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(read_data_1_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(read_data_1_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(read_data_1_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(read_data_1_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(read_data_1_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(read_data_1_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(read_data_1_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(read_data_1_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(read_data_1_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(read_data_1_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(read_data_1_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(read_data_1_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(read_data_1_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(read_data_1_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(read_data_1_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(read_data_1_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(read_data_1_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(read_data_1_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RFIFONUM(m_axi_gmem0_RFIFONUM),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(read_data_1_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .in_r(in_r),
    .S0_buf4_din(read_data_1_U0_S0_buf4_din),
    .S0_buf4_num_data_valid(S0_buf_num_data_valid),
    .S0_buf4_fifo_cap(S0_buf_fifo_cap),
    .S0_buf4_full_n(S0_buf_full_n),
    .S0_buf4_write(read_data_1_U0_S0_buf4_write),
    .D0_buf5_din(read_data_1_U0_D0_buf5_din),
    .D0_buf5_num_data_valid(D0_buf_num_data_valid),
    .D0_buf5_fifo_cap(D0_buf_fifo_cap),
    .D0_buf5_full_n(D0_buf_full_n),
    .D0_buf5_write(read_data_1_U0_D0_buf5_write),
    .u0_buf6_din(read_data_1_U0_u0_buf6_din),
    .u0_buf6_num_data_valid(u0_buf_num_data_valid),
    .u0_buf6_fifo_cap(u0_buf_fifo_cap),
    .u0_buf6_full_n(u0_buf_full_n),
    .u0_buf6_write(read_data_1_U0_u0_buf6_write),
    .count(count),
    .count_c_din(read_data_1_U0_count_c_din),
    .count_c_num_data_valid(count_c_num_data_valid),
    .count_c_fifo_cap(count_c_fifo_cap),
    .count_c_full_n(count_c_full_n),
    .count_c_write(read_data_1_U0_count_c_write),
    .ap_ext_blocking_n(read_data_1_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(read_data_1_U0_ap_str_blocking_n),
    .ap_int_blocking_n(read_data_1_U0_ap_int_blocking_n)
);

krnl_helm_compute_1 compute_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_1_U0_ap_start),
    .ap_done(compute_1_U0_ap_done),
    .ap_continue(compute_1_U0_ap_continue),
    .ap_idle(compute_1_U0_ap_idle),
    .ap_ready(compute_1_U0_ap_ready),
    .S0_buf4_dout(S0_buf_dout),
    .S0_buf4_num_data_valid(S0_buf_num_data_valid),
    .S0_buf4_fifo_cap(S0_buf_fifo_cap),
    .S0_buf4_empty_n(S0_buf_empty_n),
    .S0_buf4_read(compute_1_U0_S0_buf4_read),
    .D0_buf5_dout(D0_buf_dout),
    .D0_buf5_num_data_valid(D0_buf_num_data_valid),
    .D0_buf5_fifo_cap(D0_buf_fifo_cap),
    .D0_buf5_empty_n(D0_buf_empty_n),
    .D0_buf5_read(compute_1_U0_D0_buf5_read),
    .u0_buf6_dout(u0_buf_dout),
    .u0_buf6_num_data_valid(u0_buf_num_data_valid),
    .u0_buf6_fifo_cap(u0_buf_fifo_cap),
    .u0_buf6_empty_n(u0_buf_empty_n),
    .u0_buf6_read(compute_1_U0_u0_buf6_read),
    .v0_buf7_din(compute_1_U0_v0_buf7_din),
    .v0_buf7_num_data_valid(v0_buf_num_data_valid),
    .v0_buf7_fifo_cap(v0_buf_fifo_cap),
    .v0_buf7_full_n(v0_buf_full_n),
    .v0_buf7_write(compute_1_U0_v0_buf7_write),
    .ap_ext_blocking_n(compute_1_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(compute_1_U0_ap_str_blocking_n),
    .ap_int_blocking_n(compute_1_U0_ap_int_blocking_n)
);

krnl_helm_write_data_1 write_data_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(write_data_1_U0_ap_start),
    .ap_done(write_data_1_U0_ap_done),
    .ap_continue(write_data_1_U0_ap_continue),
    .ap_idle(write_data_1_U0_ap_idle),
    .ap_ready(write_data_1_U0_ap_ready),
    .m_axi_gmem1_AWVALID(write_data_1_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(m_axi_gmem1_AWREADY),
    .m_axi_gmem1_AWADDR(write_data_1_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(write_data_1_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(write_data_1_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(write_data_1_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(write_data_1_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(write_data_1_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(write_data_1_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(write_data_1_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(write_data_1_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(write_data_1_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(write_data_1_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(write_data_1_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(m_axi_gmem1_WREADY),
    .m_axi_gmem1_WDATA(write_data_1_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(write_data_1_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(write_data_1_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(write_data_1_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(write_data_1_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(write_data_1_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(1'b0),
    .m_axi_gmem1_ARADDR(write_data_1_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(write_data_1_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(write_data_1_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(write_data_1_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(write_data_1_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(write_data_1_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(write_data_1_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(write_data_1_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(write_data_1_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(write_data_1_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(write_data_1_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(1'b0),
    .m_axi_gmem1_RREADY(write_data_1_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(64'd0),
    .m_axi_gmem1_RLAST(1'b0),
    .m_axi_gmem1_RID(1'd0),
    .m_axi_gmem1_RFIFONUM(9'd0),
    .m_axi_gmem1_RUSER(1'd0),
    .m_axi_gmem1_RRESP(2'd0),
    .m_axi_gmem1_BVALID(m_axi_gmem1_BVALID),
    .m_axi_gmem1_BREADY(write_data_1_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(m_axi_gmem1_BRESP),
    .m_axi_gmem1_BID(m_axi_gmem1_BID),
    .m_axi_gmem1_BUSER(m_axi_gmem1_BUSER),
    .out_r_dout(out_r_c_dout),
    .out_r_num_data_valid(out_r_c_num_data_valid),
    .out_r_fifo_cap(out_r_c_fifo_cap),
    .out_r_empty_n(out_r_c_empty_n),
    .out_r_read(write_data_1_U0_out_r_read),
    .v0_buf7_dout(v0_buf_dout),
    .v0_buf7_num_data_valid(v0_buf_num_data_valid),
    .v0_buf7_fifo_cap(v0_buf_fifo_cap),
    .v0_buf7_empty_n(v0_buf_empty_n),
    .v0_buf7_read(write_data_1_U0_v0_buf7_read),
    .count_dout(count_c_dout),
    .count_num_data_valid(count_c_num_data_valid),
    .count_fifo_cap(count_c_fifo_cap),
    .count_empty_n(count_c_empty_n),
    .count_read(write_data_1_U0_count_read),
    .ap_ext_blocking_n(write_data_1_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(write_data_1_U0_ap_str_blocking_n),
    .ap_int_blocking_n(write_data_1_U0_ap_int_blocking_n)
);

krnl_helm_fifo_w64_d4_S out_r_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_out_r_c_din),
    .if_full_n(out_r_c_full_n),
    .if_write(entry_proc_U0_out_r_c_write),
    .if_dout(out_r_c_dout),
    .if_num_data_valid(out_r_c_num_data_valid),
    .if_fifo_cap(out_r_c_fifo_cap),
    .if_empty_n(out_r_c_empty_n),
    .if_read(write_data_1_U0_out_r_read)
);

krnl_helm_fifo_w64_d121_A S0_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_data_1_U0_S0_buf4_din),
    .if_full_n(S0_buf_full_n),
    .if_write(read_data_1_U0_S0_buf4_write),
    .if_dout(S0_buf_dout),
    .if_num_data_valid(S0_buf_num_data_valid),
    .if_fifo_cap(S0_buf_fifo_cap),
    .if_empty_n(S0_buf_empty_n),
    .if_read(compute_1_U0_S0_buf4_read)
);

krnl_helm_fifo_w64_d1331_A D0_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_data_1_U0_D0_buf5_din),
    .if_full_n(D0_buf_full_n),
    .if_write(read_data_1_U0_D0_buf5_write),
    .if_dout(D0_buf_dout),
    .if_num_data_valid(D0_buf_num_data_valid),
    .if_fifo_cap(D0_buf_fifo_cap),
    .if_empty_n(D0_buf_empty_n),
    .if_read(compute_1_U0_D0_buf5_read)
);

krnl_helm_fifo_w64_d1331_A u0_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_data_1_U0_u0_buf6_din),
    .if_full_n(u0_buf_full_n),
    .if_write(read_data_1_U0_u0_buf6_write),
    .if_dout(u0_buf_dout),
    .if_num_data_valid(u0_buf_num_data_valid),
    .if_fifo_cap(u0_buf_fifo_cap),
    .if_empty_n(u0_buf_empty_n),
    .if_read(compute_1_U0_u0_buf6_read)
);

krnl_helm_fifo_w32_d3_S count_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_data_1_U0_count_c_din),
    .if_full_n(count_c_full_n),
    .if_write(read_data_1_U0_count_c_write),
    .if_dout(count_c_dout),
    .if_num_data_valid(count_c_num_data_valid),
    .if_fifo_cap(count_c_fifo_cap),
    .if_empty_n(count_c_empty_n),
    .if_read(write_data_1_U0_count_read)
);

krnl_helm_fifo_w64_d1331_A v0_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_1_U0_v0_buf7_din),
    .if_full_n(v0_buf_full_n),
    .if_write(compute_1_U0_v0_buf7_write),
    .if_dout(v0_buf_dout),
    .if_num_data_valid(v0_buf_num_data_valid),
    .if_fifo_cap(v0_buf_fifo_cap),
    .if_empty_n(v0_buf_empty_n),
    .if_read(write_data_1_U0_v0_buf7_read)
);

krnl_helm_start_for_write_data_1_U0 start_for_write_data_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_data_1_U0_din),
    .if_full_n(start_for_write_data_1_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_write_data_1_U0_dout),
    .if_empty_n(start_for_write_data_1_U0_empty_n),
    .if_read(write_data_1_U0_ap_ready)
);

krnl_helm_start_for_compute_1_U0 start_for_compute_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_compute_1_U0_din),
    .if_full_n(start_for_compute_1_U0_full_n),
    .if_write(read_data_1_U0_start_write),
    .if_dout(start_for_compute_1_U0_dout),
    .if_empty_n(start_for_compute_1_U0_empty_n),
    .if_read(compute_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_read_data_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_data_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_data_1_U0_ap_ready <= ap_sync_read_data_1_U0_ap_ready;
        end
    end
end

assign ap_done = write_data_1_U0_ap_done;

assign ap_ext_blocking_cur_n = 1'b1;

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & ap_ext_blocking_cur_n);

assign ap_ext_blocking_sub_n = (write_data_1_U0_ap_ext_blocking_n & read_data_1_U0_ap_ext_blocking_n & entry_proc_U0_ap_ext_blocking_n & compute_1_U0_ap_ext_blocking_n);

assign ap_idle = (write_data_1_U0_ap_idle & read_data_1_U0_ap_idle & entry_proc_U0_ap_idle & compute_1_U0_ap_idle);

assign ap_int_blocking_cur_n = 1'b1;

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_int_blocking_sub_n = (write_data_1_U0_ap_int_blocking_n & read_data_1_U0_ap_int_blocking_n & entry_proc_U0_ap_int_blocking_n & compute_1_U0_ap_int_blocking_n);

assign ap_ready = ap_sync_ready;

assign ap_str_blocking_cur_n = 1'b1;

assign ap_str_blocking_n = (ap_str_blocking_sub_n & ap_str_blocking_cur_n);

assign ap_str_blocking_sub_n = (write_data_1_U0_ap_str_blocking_n & read_data_1_U0_ap_str_blocking_n & entry_proc_U0_ap_str_blocking_n & compute_1_U0_ap_str_blocking_n);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_read_data_1_U0_ap_ready = (read_data_1_U0_ap_ready | ap_sync_reg_read_data_1_U0_ap_ready);

assign ap_sync_ready = (ap_sync_read_data_1_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign compute_1_U0_ap_continue = 1'b1;

assign compute_1_U0_ap_start = start_for_compute_1_U0_empty_n;

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign m_axi_gmem0_ARADDR = read_data_1_U0_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = read_data_1_U0_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = read_data_1_U0_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = read_data_1_U0_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = read_data_1_U0_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = read_data_1_U0_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = read_data_1_U0_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = read_data_1_U0_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = read_data_1_U0_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = read_data_1_U0_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = read_data_1_U0_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_ARVALID = read_data_1_U0_m_axi_gmem0_ARVALID;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_RREADY = read_data_1_U0_m_axi_gmem0_RREADY;

assign m_axi_gmem0_WDATA = 64'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 8'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_ARADDR = 64'd0;

assign m_axi_gmem1_ARBURST = 2'd0;

assign m_axi_gmem1_ARCACHE = 4'd0;

assign m_axi_gmem1_ARID = 1'd0;

assign m_axi_gmem1_ARLEN = 32'd0;

assign m_axi_gmem1_ARLOCK = 2'd0;

assign m_axi_gmem1_ARPROT = 3'd0;

assign m_axi_gmem1_ARQOS = 4'd0;

assign m_axi_gmem1_ARREGION = 4'd0;

assign m_axi_gmem1_ARSIZE = 3'd0;

assign m_axi_gmem1_ARUSER = 1'd0;

assign m_axi_gmem1_ARVALID = 1'b0;

assign m_axi_gmem1_AWADDR = write_data_1_U0_m_axi_gmem1_AWADDR;

assign m_axi_gmem1_AWBURST = write_data_1_U0_m_axi_gmem1_AWBURST;

assign m_axi_gmem1_AWCACHE = write_data_1_U0_m_axi_gmem1_AWCACHE;

assign m_axi_gmem1_AWID = write_data_1_U0_m_axi_gmem1_AWID;

assign m_axi_gmem1_AWLEN = write_data_1_U0_m_axi_gmem1_AWLEN;

assign m_axi_gmem1_AWLOCK = write_data_1_U0_m_axi_gmem1_AWLOCK;

assign m_axi_gmem1_AWPROT = write_data_1_U0_m_axi_gmem1_AWPROT;

assign m_axi_gmem1_AWQOS = write_data_1_U0_m_axi_gmem1_AWQOS;

assign m_axi_gmem1_AWREGION = write_data_1_U0_m_axi_gmem1_AWREGION;

assign m_axi_gmem1_AWSIZE = write_data_1_U0_m_axi_gmem1_AWSIZE;

assign m_axi_gmem1_AWUSER = write_data_1_U0_m_axi_gmem1_AWUSER;

assign m_axi_gmem1_AWVALID = write_data_1_U0_m_axi_gmem1_AWVALID;

assign m_axi_gmem1_BREADY = write_data_1_U0_m_axi_gmem1_BREADY;

assign m_axi_gmem1_RREADY = 1'b0;

assign m_axi_gmem1_WDATA = write_data_1_U0_m_axi_gmem1_WDATA;

assign m_axi_gmem1_WID = write_data_1_U0_m_axi_gmem1_WID;

assign m_axi_gmem1_WLAST = write_data_1_U0_m_axi_gmem1_WLAST;

assign m_axi_gmem1_WSTRB = write_data_1_U0_m_axi_gmem1_WSTRB;

assign m_axi_gmem1_WUSER = write_data_1_U0_m_axi_gmem1_WUSER;

assign m_axi_gmem1_WVALID = write_data_1_U0_m_axi_gmem1_WVALID;

assign read_data_1_U0_ap_continue = 1'b1;

assign read_data_1_U0_ap_start = ((ap_sync_reg_read_data_1_U0_ap_ready ^ 1'b1) & ap_start);

assign start_for_compute_1_U0_din = 1'b1;

assign start_for_write_data_1_U0_din = 1'b1;

assign write_data_1_U0_ap_continue = ap_continue;

assign write_data_1_U0_ap_start = start_for_write_data_1_U0_empty_n;

endmodule //krnl_helm_dataflow_in_loop_VITIS_LOOP_112_1
