// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module krnl_helm_compute_1_Pipeline_VITIS_LOOP_16_5_VITIS_LOOP_17_6_VITIS_LOOP_18_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S_buf_address0,
        S_buf_ce0,
        S_buf_q0,
        t0_address0,
        t0_ce0,
        t0_we0,
        t0_d0,
        t1_address0,
        t1_ce0,
        t1_q0,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n,
        grp_fu_170_p_din0,
        grp_fu_170_p_din1,
        grp_fu_170_p_opcode,
        grp_fu_170_p_dout0,
        grp_fu_170_p_ce,
        grp_fu_174_p_din0,
        grp_fu_174_p_din1,
        grp_fu_174_p_dout0,
        grp_fu_174_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 11'd1;
parameter    ap_ST_fsm_pp0_stage1 = 11'd2;
parameter    ap_ST_fsm_pp0_stage2 = 11'd4;
parameter    ap_ST_fsm_pp0_stage3 = 11'd8;
parameter    ap_ST_fsm_pp0_stage4 = 11'd16;
parameter    ap_ST_fsm_pp0_stage5 = 11'd32;
parameter    ap_ST_fsm_pp0_stage6 = 11'd64;
parameter    ap_ST_fsm_pp0_stage7 = 11'd128;
parameter    ap_ST_fsm_pp0_stage8 = 11'd256;
parameter    ap_ST_fsm_pp0_stage9 = 11'd512;
parameter    ap_ST_fsm_pp0_stage10 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] S_buf_address0;
output   S_buf_ce0;
input  [63:0] S_buf_q0;
output  [10:0] t0_address0;
output   t0_ce0;
output   t0_we0;
output  [63:0] t0_d0;
output  [10:0] t1_address0;
output   t1_ce0;
input  [63:0] t1_q0;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;
output  [63:0] grp_fu_170_p_din0;
output  [63:0] grp_fu_170_p_din1;
output  [1:0] grp_fu_170_p_opcode;
input  [63:0] grp_fu_170_p_dout0;
output   grp_fu_170_p_ce;
output  [63:0] grp_fu_174_p_din0;
output  [63:0] grp_fu_174_p_din1;
input  [63:0] grp_fu_174_p_dout0;
output   grp_fu_174_p_ce;

reg ap_idle;
reg[6:0] S_buf_address0;
reg S_buf_ce0;
reg t0_ce0;
reg t0_we0;
reg[10:0] t1_address0;
reg t1_ce0;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_state11_pp0_stage10_iter0;
wire    ap_block_state22_pp0_stage10_iter1;
wire    ap_block_state33_pp0_stage10_iter2;
wire    ap_block_state44_pp0_stage10_iter3;
wire    ap_block_state55_pp0_stage10_iter4;
wire    ap_block_state66_pp0_stage10_iter5;
wire    ap_block_pp0_stage10_subdone;
reg   [0:0] icmp_ln16_reg_904;
reg    ap_condition_exit_pp0_iter0_stage10;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [63:0] reg_334;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state16_pp0_stage4_iter1;
wire    ap_block_state27_pp0_stage4_iter2;
wire    ap_block_state38_pp0_stage4_iter3;
wire    ap_block_state49_pp0_stage4_iter4;
wire    ap_block_state60_pp0_stage4_iter5;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state10_pp0_stage9_iter0;
wire    ap_block_state21_pp0_stage9_iter1;
wire    ap_block_state32_pp0_stage9_iter2;
wire    ap_block_state43_pp0_stage9_iter3;
wire    ap_block_state54_pp0_stage9_iter4;
wire    ap_block_state65_pp0_stage9_iter5;
wire    ap_block_pp0_stage9_11001;
reg   [63:0] reg_339;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state15_pp0_stage3_iter1;
wire    ap_block_state26_pp0_stage3_iter2;
wire    ap_block_state37_pp0_stage3_iter3;
wire    ap_block_state48_pp0_stage3_iter4;
wire    ap_block_state59_pp0_stage3_iter5;
wire    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state9_pp0_stage8_iter0;
wire    ap_block_state20_pp0_stage8_iter1;
wire    ap_block_state31_pp0_stage8_iter2;
wire    ap_block_state42_pp0_stage8_iter3;
wire    ap_block_state53_pp0_stage8_iter4;
wire    ap_block_state64_pp0_stage8_iter5;
wire    ap_block_pp0_stage8_11001;
reg   [63:0] reg_344;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state14_pp0_stage2_iter1;
wire    ap_block_state25_pp0_stage2_iter2;
wire    ap_block_state36_pp0_stage2_iter3;
wire    ap_block_state47_pp0_stage2_iter4;
wire    ap_block_state58_pp0_stage2_iter5;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state8_pp0_stage7_iter0;
wire    ap_block_state19_pp0_stage7_iter1;
wire    ap_block_state30_pp0_stage7_iter2;
wire    ap_block_state41_pp0_stage7_iter3;
wire    ap_block_state52_pp0_stage7_iter4;
wire    ap_block_state63_pp0_stage7_iter5;
wire    ap_block_pp0_stage7_11001;
reg   [63:0] reg_349;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state13_pp0_stage1_iter1;
wire    ap_block_state24_pp0_stage1_iter2;
wire    ap_block_state35_pp0_stage1_iter3;
wire    ap_block_state46_pp0_stage1_iter4;
wire    ap_block_state57_pp0_stage1_iter5;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_state18_pp0_stage6_iter1;
wire    ap_block_state29_pp0_stage6_iter2;
wire    ap_block_state40_pp0_stage6_iter3;
wire    ap_block_state51_pp0_stage6_iter4;
wire    ap_block_state62_pp0_stage6_iter5;
wire    ap_block_pp0_stage6_11001;
reg   [63:0] reg_354;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state12_pp0_stage0_iter1;
wire    ap_block_state23_pp0_stage0_iter2;
wire    ap_block_state34_pp0_stage0_iter3;
wire    ap_block_state45_pp0_stage0_iter4;
wire    ap_block_state56_pp0_stage0_iter5;
wire    ap_block_state67_pp0_stage0_iter6;
wire    ap_block_pp0_stage0_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_state17_pp0_stage5_iter1;
wire    ap_block_state28_pp0_stage5_iter2;
wire    ap_block_state39_pp0_stage5_iter3;
wire    ap_block_state50_pp0_stage5_iter4;
wire    ap_block_state61_pp0_stage5_iter5;
wire    ap_block_pp0_stage5_11001;
wire    ap_block_pp0_stage10_11001;
reg   [3:0] c2_reg_888;
reg   [10:0] indvar_flatten93_load_reg_894;
wire   [10:0] empty_71_fu_395_p2;
reg   [10:0] empty_71_reg_899;
wire   [0:0] icmp_ln16_fu_401_p2;
reg   [0:0] icmp_ln16_reg_904_pp0_iter1_reg;
reg   [0:0] icmp_ln16_reg_904_pp0_iter2_reg;
reg   [0:0] icmp_ln16_reg_904_pp0_iter3_reg;
reg   [0:0] icmp_ln16_reg_904_pp0_iter4_reg;
reg   [7:0] indvar_flatten56_load_reg_908;
wire   [0:0] icmp_ln17_fu_413_p2;
reg   [0:0] icmp_ln17_reg_913;
wire   [0:0] and_ln16_fu_431_p2;
reg   [0:0] and_ln16_reg_923;
wire   [3:0] select_ln17_fu_443_p3;
reg   [3:0] select_ln17_reg_930;
wire   [3:0] add_ln17_fu_478_p2;
reg   [3:0] add_ln17_reg_940;
wire   [10:0] select_ln17_2_fu_494_p3;
reg   [10:0] select_ln17_2_reg_945;
wire   [6:0] mul_ln16_1_fu_544_p2;
reg   [6:0] mul_ln16_1_reg_955;
wire   [6:0] empty_fu_563_p2;
reg   [6:0] empty_reg_974;
reg   [63:0] S_buf_load_11_reg_979;
wire   [10:0] grp_fu_837_p3;
reg   [10:0] add_ln23_reg_989;
reg   [63:0] S_buf_load_12_reg_1008;
reg   [63:0] t1_load_reg_1023;
reg   [63:0] S_buf_load_13_reg_1033;
wire   [10:0] grp_fu_845_p3;
reg   [10:0] add_ln20_reg_1043;
reg   [10:0] add_ln20_reg_1043_pp0_iter1_reg;
reg   [10:0] add_ln20_reg_1043_pp0_iter2_reg;
reg   [10:0] add_ln20_reg_1043_pp0_iter3_reg;
reg   [10:0] add_ln20_reg_1043_pp0_iter4_reg;
reg   [10:0] add_ln20_reg_1043_pp0_iter5_reg;
reg   [63:0] t1_load_1_reg_1048;
reg   [63:0] S_buf_load_14_reg_1058;
reg   [63:0] t1_load_2_reg_1068;
reg   [63:0] S_buf_load_15_reg_1078;
reg   [63:0] t1_load_3_reg_1088;
reg   [63:0] S_buf_load_16_reg_1098;
reg   [63:0] t1_load_4_reg_1108;
reg   [63:0] S_buf_load_17_reg_1118;
reg   [63:0] t1_load_5_reg_1128;
reg   [63:0] S_buf_load_18_reg_1138;
wire   [6:0] add_ln16_9_fu_758_p2;
reg   [6:0] add_ln16_9_reg_1148;
wire   [6:0] add_ln16_10_fu_763_p2;
reg   [6:0] add_ln16_10_reg_1153;
reg   [63:0] mul91_i_reg_1158;
reg   [63:0] t1_load_6_reg_1163;
reg   [63:0] S_buf_load_19_reg_1173;
reg   [63:0] mul91_i_1_reg_1183;
reg   [63:0] t1_load_7_reg_1188;
reg   [63:0] S_buf_load_20_reg_1198;
reg   [63:0] mul91_i_2_reg_1208;
reg   [63:0] t1_load_8_reg_1213;
reg   [63:0] S_buf_load_21_reg_1223;
reg   [63:0] mul91_i_3_reg_1228;
reg   [63:0] mul91_i_3_reg_1228_pp0_iter2_reg;
reg   [63:0] t1_load_9_reg_1233;
reg   [63:0] mul91_i_4_reg_1243;
reg   [63:0] mul91_i_4_reg_1243_pp0_iter2_reg;
reg   [63:0] t1_load_10_reg_1248;
reg   [63:0] mul91_i_5_reg_1253;
reg   [63:0] mul91_i_5_reg_1253_pp0_iter2_reg;
reg   [63:0] mul91_i_6_reg_1258;
reg   [63:0] mul91_i_6_reg_1258_pp0_iter2_reg;
reg   [63:0] mul91_i_6_reg_1258_pp0_iter3_reg;
reg   [63:0] mul91_i_7_reg_1263;
reg   [63:0] mul91_i_7_reg_1263_pp0_iter2_reg;
reg   [63:0] mul91_i_7_reg_1263_pp0_iter3_reg;
reg   [63:0] mul91_i_8_reg_1268;
reg   [63:0] mul91_i_8_reg_1268_pp0_iter2_reg;
reg   [63:0] mul91_i_8_reg_1268_pp0_iter3_reg;
reg   [63:0] mul91_i_9_reg_1273;
reg   [63:0] mul91_i_9_reg_1273_pp0_iter2_reg;
reg   [63:0] mul91_i_9_reg_1273_pp0_iter3_reg;
reg   [63:0] mul91_i_9_reg_1273_pp0_iter4_reg;
reg   [63:0] mul91_i_s_reg_1278;
reg   [63:0] mul91_i_s_reg_1278_pp0_iter2_reg;
reg   [63:0] mul91_i_s_reg_1278_pp0_iter3_reg;
reg   [63:0] mul91_i_s_reg_1278_pp0_iter4_reg;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln16_2_fu_550_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln16_3_fu_579_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln23_1_fu_584_p1;
wire   [63:0] zext_ln16_4_fu_598_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln23_2_fu_643_p1;
wire   [63:0] zext_ln16_5_fu_653_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln23_3_fu_663_p1;
wire   [63:0] zext_ln16_6_fu_673_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln23_4_fu_683_p1;
wire   [63:0] zext_ln16_7_fu_693_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln23_5_fu_703_p1;
wire   [63:0] zext_ln16_8_fu_713_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln23_6_fu_723_p1;
wire   [63:0] zext_ln16_9_fu_733_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln23_7_fu_743_p1;
wire   [63:0] zext_ln16_10_fu_753_p1;
wire    ap_block_pp0_stage10;
wire   [63:0] zext_ln23_8_fu_773_p1;
wire   [63:0] zext_ln16_11_fu_795_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln23_9_fu_804_p1;
wire   [63:0] zext_ln16_12_fu_809_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln23_10_fu_818_p1;
wire   [63:0] zext_ln23_11_fu_828_p1;
wire   [63:0] zext_ln20_fu_833_p1;
reg   [3:0] c3_fu_106;
wire   [3:0] add_ln18_fu_455_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_c3_load;
reg   [3:0] c2_1_fu_110;
wire   [3:0] select_ln17_3_fu_501_p3;
reg   [3:0] ap_sig_allocacmp_c2;
reg   [7:0] indvar_flatten56_fu_114;
wire   [7:0] select_ln17_4_fu_783_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten56_load;
reg   [3:0] c1_fu_118;
wire   [3:0] select_ln16_1_fu_522_p3;
reg   [10:0] indvar_flatten93_fu_122;
wire   [10:0] add_ln16_fu_569_p2;
reg   [10:0] ap_sig_allocacmp_indvar_flatten93_load;
reg   [63:0] grp_fu_325_p0;
reg   [63:0] grp_fu_325_p1;
reg   [63:0] grp_fu_330_p0;
reg   [63:0] grp_fu_330_p1;
wire   [3:0] empty_71_fu_395_p0;
wire   [7:0] empty_71_fu_395_p1;
wire   [0:0] icmp_ln18_fu_425_p2;
wire   [0:0] xor_ln16_fu_419_p2;
wire   [0:0] or_ln17_fu_437_p2;
wire   [3:0] select_ln16_fu_466_p3;
wire   [3:0] p_mid154_fu_488_p0;
wire   [7:0] p_mid154_fu_488_p1;
wire   [10:0] p_mid154_fu_488_p2;
wire   [10:0] select_ln16_5_fu_472_p3;
wire   [3:0] add_ln16_11_fu_516_p2;
wire   [3:0] select_ln16_3_fu_533_p3;
wire   [3:0] mul_ln16_1_fu_544_p0;
wire   [4:0] mul_ln16_1_fu_544_p1;
wire   [3:0] empty_fu_563_p0;
wire   [4:0] empty_fu_563_p1;
wire   [6:0] add_ln16_1_fu_574_p2;
wire   [6:0] add_ln16_2_fu_593_p2;
wire   [3:0] p_mid152_fu_612_p0;
wire   [4:0] p_mid152_fu_612_p1;
wire   [6:0] p_mid152_fu_612_p2;
wire   [6:0] select_ln16_4_fu_603_p3;
wire   [6:0] select_ln17_1_fu_618_p3;
wire   [6:0] c3_1_cast13_fu_625_p1;
wire   [6:0] add_ln20_1_fu_628_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_1_fu_638_p2;
wire   [6:0] add_ln16_3_fu_648_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_2_fu_658_p2;
wire   [6:0] add_ln16_4_fu_668_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_3_fu_678_p2;
wire   [6:0] add_ln16_5_fu_688_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_4_fu_698_p2;
wire   [6:0] add_ln16_6_fu_708_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_5_fu_718_p2;
wire   [6:0] add_ln16_7_fu_728_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_6_fu_738_p2;
wire   [6:0] add_ln16_8_fu_748_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_7_fu_768_p2;
wire   [7:0] add_ln17_1_fu_778_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_8_fu_799_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_9_fu_813_p2;
(* use_dsp48 = "no" *) wire   [10:0] add_ln23_10_fu_823_p2;
wire   [3:0] grp_fu_837_p0;
wire   [3:0] grp_fu_837_p1;
wire   [3:0] grp_fu_845_p0;
wire   [6:0] grp_fu_845_p1;
wire   [6:0] grp_fu_845_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter5_stage0;
reg    ap_idle_pp0_0to4;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [10:0] ap_NS_fsm;
reg    ap_idle_pp0_1to6;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage0_00001;
wire    ap_block_pp0_stage5_00001;
wire    ap_block_pp0_stage10_00001;
wire    ap_block_pp0_stage4_00001;
wire    ap_block_pp0_stage9_00001;
wire    ap_block_pp0_stage3_00001;
wire    ap_block_pp0_stage8_00001;
wire    ap_block_pp0_stage2_00001;
wire    ap_block_pp0_stage7_00001;
wire    ap_block_pp0_stage1_00001;
wire    ap_block_pp0_stage6_00001;
wire   [10:0] empty_71_fu_395_p00;
wire   [6:0] empty_fu_563_p00;
wire   [7:0] grp_fu_837_p00;
wire   [10:0] grp_fu_845_p00;
wire   [10:0] grp_fu_845_p20;
wire   [6:0] mul_ln16_1_fu_544_p00;
wire   [6:0] p_mid152_fu_612_p00;
wire   [10:0] p_mid154_fu_488_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

krnl_helm_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U67(
    .din0(empty_71_fu_395_p0),
    .din1(empty_71_fu_395_p1),
    .dout(empty_71_fu_395_p2)
);

krnl_helm_mul_4ns_8ns_11_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 11 ))
mul_4ns_8ns_11_1_1_U68(
    .din0(p_mid154_fu_488_p0),
    .din1(p_mid154_fu_488_p1),
    .dout(p_mid154_fu_488_p2)
);

krnl_helm_mul_4ns_5ns_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 7 ))
mul_4ns_5ns_7_1_1_U69(
    .din0(mul_ln16_1_fu_544_p0),
    .din1(mul_ln16_1_fu_544_p1),
    .dout(mul_ln16_1_fu_544_p2)
);

krnl_helm_mul_4ns_5ns_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 7 ))
mul_4ns_5ns_7_1_1_U70(
    .din0(empty_fu_563_p0),
    .din1(empty_fu_563_p1),
    .dout(empty_fu_563_p2)
);

krnl_helm_mul_4ns_5ns_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 7 ))
mul_4ns_5ns_7_1_1_U71(
    .din0(p_mid152_fu_612_p0),
    .din1(p_mid152_fu_612_p1),
    .dout(p_mid152_fu_612_p2)
);

krnl_helm_mac_muladd_4ns_4ns_11ns_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
mac_muladd_4ns_4ns_11ns_11_4_1_U72(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_837_p0),
    .din1(grp_fu_837_p1),
    .din2(select_ln17_2_reg_945),
    .ce(1'b1),
    .dout(grp_fu_837_p3)
);

krnl_helm_mac_muladd_4ns_7ns_7ns_11_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .dout_WIDTH( 11 ))
mac_muladd_4ns_7ns_7ns_11_4_1_U73(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_845_p0),
    .din1(grp_fu_845_p1),
    .din2(grp_fu_845_p2),
    .ce(1'b1),
    .dout(grp_fu_845_p3)
);

krnl_helm_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage10),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage10)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage10_subdone) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter5_stage0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter5_stage0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter5_stage0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter5_stage0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter5_stage0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c1_fu_118 <= 4'd0;
    end else if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        c1_fu_118 <= select_ln16_1_fu_522_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c2_1_fu_110 <= 4'd0;
    end else if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        c2_1_fu_110 <= select_ln17_3_fu_501_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln16_fu_401_p2 == 1'd0))) begin
            c3_fu_106 <= add_ln18_fu_455_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c3_fu_106 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten56_fu_114 <= 8'd0;
    end else if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        indvar_flatten56_fu_114 <= select_ln17_4_fu_783_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten93_fu_122 <= 11'd0;
    end else if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        indvar_flatten93_fu_122 <= add_ln16_fu_569_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        S_buf_load_11_reg_979 <= S_buf_q0;
        add_ln23_reg_989 <= grp_fu_837_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        S_buf_load_12_reg_1008 <= S_buf_q0;
        t1_load_reg_1023 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        S_buf_load_13_reg_1033 <= S_buf_q0;
        add_ln20_reg_1043 <= grp_fu_845_p3;
        t1_load_1_reg_1048 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        S_buf_load_14_reg_1058 <= S_buf_q0;
        t1_load_2_reg_1068 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        S_buf_load_15_reg_1078 <= S_buf_q0;
        t1_load_3_reg_1088 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        S_buf_load_16_reg_1098 <= S_buf_q0;
        t1_load_4_reg_1108 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        S_buf_load_17_reg_1118 <= S_buf_q0;
        t1_load_5_reg_1128 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        S_buf_load_18_reg_1138 <= S_buf_q0;
        mul91_i_reg_1158 <= grp_fu_174_p_dout0;
        t1_load_6_reg_1163 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_buf_load_19_reg_1173 <= S_buf_q0;
        mul91_i_1_reg_1183 <= grp_fu_174_p_dout0;
        t1_load_7_reg_1188 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        S_buf_load_20_reg_1198 <= S_buf_q0;
        mul91_i_2_reg_1208 <= grp_fu_174_p_dout0;
        t1_load_8_reg_1213 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        S_buf_load_21_reg_1223 <= S_buf_q0;
        mul91_i_3_reg_1228 <= grp_fu_174_p_dout0;
        t1_load_9_reg_1233 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage10_11001) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        add_ln16_10_reg_1153 <= add_ln16_10_fu_763_p2;
        add_ln16_9_reg_1148 <= add_ln16_9_fu_758_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln17_reg_940 <= add_ln17_fu_478_p2;
        select_ln17_2_reg_945 <= select_ln17_2_fu_494_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        add_ln20_reg_1043_pp0_iter1_reg <= add_ln20_reg_1043;
        add_ln20_reg_1043_pp0_iter2_reg <= add_ln20_reg_1043_pp0_iter1_reg;
        add_ln20_reg_1043_pp0_iter3_reg <= add_ln20_reg_1043_pp0_iter2_reg;
        add_ln20_reg_1043_pp0_iter4_reg <= add_ln20_reg_1043_pp0_iter3_reg;
        add_ln20_reg_1043_pp0_iter5_reg <= add_ln20_reg_1043_pp0_iter4_reg;
        mul91_i_6_reg_1258_pp0_iter2_reg <= mul91_i_6_reg_1258;
        mul91_i_6_reg_1258_pp0_iter3_reg <= mul91_i_6_reg_1258_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln16_fu_401_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln16_reg_923 <= and_ln16_fu_431_p2;
        icmp_ln17_reg_913 <= icmp_ln17_fu_413_p2;
        indvar_flatten56_load_reg_908 <= ap_sig_allocacmp_indvar_flatten56_load;
        select_ln17_reg_930 <= select_ln17_fu_443_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        c2_reg_888 <= ap_sig_allocacmp_c2;
        empty_71_reg_899 <= empty_71_fu_395_p2;
        icmp_ln16_reg_904 <= icmp_ln16_fu_401_p2;
        icmp_ln16_reg_904_pp0_iter1_reg <= icmp_ln16_reg_904;
        icmp_ln16_reg_904_pp0_iter2_reg <= icmp_ln16_reg_904_pp0_iter1_reg;
        icmp_ln16_reg_904_pp0_iter3_reg <= icmp_ln16_reg_904_pp0_iter2_reg;
        icmp_ln16_reg_904_pp0_iter4_reg <= icmp_ln16_reg_904_pp0_iter3_reg;
        indvar_flatten93_load_reg_894 <= ap_sig_allocacmp_indvar_flatten93_load;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln17_reg_913 == 1'd0) & (1'd0 == and_ln16_reg_923) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_reg_974 <= empty_fu_563_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul91_i_3_reg_1228_pp0_iter2_reg <= mul91_i_3_reg_1228;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul91_i_4_reg_1243 <= grp_fu_174_p_dout0;
        t1_load_10_reg_1248 <= t1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul91_i_4_reg_1243_pp0_iter2_reg <= mul91_i_4_reg_1243;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul91_i_5_reg_1253 <= grp_fu_174_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        mul91_i_5_reg_1253_pp0_iter2_reg <= mul91_i_5_reg_1253;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        mul91_i_6_reg_1258 <= grp_fu_174_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        mul91_i_7_reg_1263 <= grp_fu_174_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        mul91_i_7_reg_1263_pp0_iter2_reg <= mul91_i_7_reg_1263;
        mul91_i_7_reg_1263_pp0_iter3_reg <= mul91_i_7_reg_1263_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        mul91_i_8_reg_1268 <= grp_fu_174_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        mul91_i_8_reg_1268_pp0_iter2_reg <= mul91_i_8_reg_1268;
        mul91_i_8_reg_1268_pp0_iter3_reg <= mul91_i_8_reg_1268_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        mul91_i_9_reg_1273 <= grp_fu_174_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage8_11001) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        mul91_i_9_reg_1273_pp0_iter2_reg <= mul91_i_9_reg_1273;
        mul91_i_9_reg_1273_pp0_iter3_reg <= mul91_i_9_reg_1273_pp0_iter2_reg;
        mul91_i_9_reg_1273_pp0_iter4_reg <= mul91_i_9_reg_1273_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        mul91_i_s_reg_1278 <= grp_fu_174_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage9_11001) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        mul91_i_s_reg_1278_pp0_iter2_reg <= mul91_i_s_reg_1278;
        mul91_i_s_reg_1278_pp0_iter3_reg <= mul91_i_s_reg_1278_pp0_iter2_reg;
        mul91_i_s_reg_1278_pp0_iter4_reg <= mul91_i_s_reg_1278_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln16_reg_904 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_ln16_1_reg_955 <= mul_ln16_1_fu_544_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        reg_334 <= grp_fu_170_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_339 <= grp_fu_170_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_344 <= grp_fu_170_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        reg_349 <= grp_fu_170_p_dout0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_354 <= grp_fu_170_p_dout0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        S_buf_address0 = zext_ln16_12_fu_809_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_buf_address0 = zext_ln16_11_fu_795_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        S_buf_address0 = zext_ln16_10_fu_753_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        S_buf_address0 = zext_ln16_9_fu_733_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        S_buf_address0 = zext_ln16_8_fu_713_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        S_buf_address0 = zext_ln16_7_fu_693_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        S_buf_address0 = zext_ln16_6_fu_673_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        S_buf_address0 = zext_ln16_5_fu_653_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        S_buf_address0 = zext_ln16_4_fu_598_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        S_buf_address0 = zext_ln16_3_fu_579_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        S_buf_address0 = zext_ln16_2_fu_550_p1;
    end else begin
        S_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        S_buf_ce0 = 1'b1;
    end else begin
        S_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln16_reg_904 == 1'd1) & (1'b0 == ap_block_pp0_stage10_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_condition_exit_pp0_iter0_stage10 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage10 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1) & (icmp_ln16_reg_904_pp0_iter4_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter5_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to6 = 1'b1;
    end else begin
        ap_idle_pp0_1to6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage10_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c2 = 4'd0;
    end else begin
        ap_sig_allocacmp_c2 = c2_1_fu_110;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c3_load = 4'd0;
    end else begin
        ap_sig_allocacmp_c3_load = c3_fu_106;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten56_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten56_load = indvar_flatten56_fu_114;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten93_load = 11'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten93_load = indvar_flatten93_fu_122;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)))) begin
        grp_fu_325_p0 = reg_354;
    end else if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        grp_fu_325_p0 = reg_349;
    end else if ((((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_325_p0 = reg_344;
    end else if ((((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        grp_fu_325_p0 = reg_339;
    end else if ((((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_325_p0 = reg_334;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_325_p0 = mul91_i_reg_1158;
    end else begin
        grp_fu_325_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_325_p1 = mul91_i_s_reg_1278_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_325_p1 = mul91_i_9_reg_1273_pp0_iter4_reg;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_325_p1 = mul91_i_8_reg_1268_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_325_p1 = mul91_i_7_reg_1263_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_325_p1 = mul91_i_6_reg_1258_pp0_iter3_reg;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_325_p1 = mul91_i_5_reg_1253_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_325_p1 = mul91_i_4_reg_1243_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_325_p1 = mul91_i_3_reg_1228_pp0_iter2_reg;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_325_p1 = mul91_i_2_reg_1208;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_325_p1 = mul91_i_1_reg_1183;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_325_p1 = 64'd0;
    end else begin
        grp_fu_325_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_330_p0 = S_buf_load_21_reg_1223;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_330_p0 = S_buf_load_20_reg_1198;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_330_p0 = S_buf_load_19_reg_1173;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_330_p0 = S_buf_load_18_reg_1138;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_330_p0 = S_buf_load_17_reg_1118;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_330_p0 = S_buf_load_16_reg_1098;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_330_p0 = S_buf_load_15_reg_1078;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_330_p0 = S_buf_load_14_reg_1058;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_330_p0 = S_buf_load_13_reg_1033;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_330_p0 = S_buf_load_12_reg_1008;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_330_p0 = S_buf_load_11_reg_979;
    end else begin
        grp_fu_330_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_330_p1 = t1_load_10_reg_1248;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        grp_fu_330_p1 = t1_load_9_reg_1233;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        grp_fu_330_p1 = t1_load_8_reg_1213;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_330_p1 = t1_load_7_reg_1188;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_330_p1 = t1_load_6_reg_1163;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        grp_fu_330_p1 = t1_load_5_reg_1128;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        grp_fu_330_p1 = t1_load_4_reg_1108;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        grp_fu_330_p1 = t1_load_3_reg_1088;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_330_p1 = t1_load_2_reg_1068;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_330_p1 = t1_load_1_reg_1048;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_330_p1 = t1_load_reg_1023;
    end else begin
        grp_fu_330_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t0_ce0 = 1'b1;
    end else begin
        t0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t0_we0 = 1'b1;
    end else begin
        t0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        t1_address0 = zext_ln23_11_fu_828_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        t1_address0 = zext_ln23_10_fu_818_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t1_address0 = zext_ln23_9_fu_804_p1;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        t1_address0 = zext_ln23_8_fu_773_p1;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        t1_address0 = zext_ln23_7_fu_743_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        t1_address0 = zext_ln23_6_fu_723_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        t1_address0 = zext_ln23_5_fu_703_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        t1_address0 = zext_ln23_4_fu_683_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        t1_address0 = zext_ln23_3_fu_663_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        t1_address0 = zext_ln23_2_fu_643_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        t1_address0 = zext_ln23_1_fu_584_p1;
    end else begin
        t1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage10_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage8_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage9_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)))) begin
        t1_ce0 = 1'b1;
    end else begin
        t1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter5_stage0) & (ap_idle_pp0_0to4 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to6 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln16_10_fu_763_p2 = (mul_ln16_1_reg_955 + 7'd10);

assign add_ln16_11_fu_516_p2 = (c1_fu_118 + 4'd1);

assign add_ln16_1_fu_574_p2 = (mul_ln16_1_reg_955 + 7'd1);

assign add_ln16_2_fu_593_p2 = (mul_ln16_1_reg_955 + 7'd2);

assign add_ln16_3_fu_648_p2 = (mul_ln16_1_reg_955 + 7'd3);

assign add_ln16_4_fu_668_p2 = (mul_ln16_1_reg_955 + 7'd4);

assign add_ln16_5_fu_688_p2 = (mul_ln16_1_reg_955 + 7'd5);

assign add_ln16_6_fu_708_p2 = (mul_ln16_1_reg_955 + 7'd6);

assign add_ln16_7_fu_728_p2 = (mul_ln16_1_reg_955 + 7'd7);

assign add_ln16_8_fu_748_p2 = (mul_ln16_1_reg_955 + 7'd8);

assign add_ln16_9_fu_758_p2 = (mul_ln16_1_reg_955 + 7'd9);

assign add_ln16_fu_569_p2 = (indvar_flatten93_load_reg_894 + 11'd1);

assign add_ln17_1_fu_778_p2 = (indvar_flatten56_load_reg_908 + 8'd1);

assign add_ln17_fu_478_p2 = (select_ln16_fu_466_p3 + 4'd1);

assign add_ln18_fu_455_p2 = (select_ln17_fu_443_p3 + 4'd1);

assign add_ln20_1_fu_628_p2 = (select_ln17_1_fu_618_p3 + c3_1_cast13_fu_625_p1);

assign add_ln23_10_fu_823_p2 = (add_ln23_reg_989 + 11'd10);

assign add_ln23_1_fu_638_p2 = (add_ln23_reg_989 + 11'd1);

assign add_ln23_2_fu_658_p2 = (add_ln23_reg_989 + 11'd2);

assign add_ln23_3_fu_678_p2 = (add_ln23_reg_989 + 11'd3);

assign add_ln23_4_fu_698_p2 = (add_ln23_reg_989 + 11'd4);

assign add_ln23_5_fu_718_p2 = (add_ln23_reg_989 + 11'd5);

assign add_ln23_6_fu_738_p2 = (add_ln23_reg_989 + 11'd6);

assign add_ln23_7_fu_768_p2 = (add_ln23_reg_989 + 11'd7);

assign add_ln23_8_fu_799_p2 = (add_ln23_reg_989 + 11'd8);

assign add_ln23_9_fu_813_p2 = (add_ln23_reg_989 + 11'd9);

assign and_ln16_fu_431_p2 = (xor_ln16_fu_419_p2 & icmp_ln18_fu_425_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd9];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage10_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage8_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage9_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage10_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage6_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage7_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage8_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage9_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage10_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage5_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage6_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage7_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage8_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage9_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage10_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage4_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage5_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage6_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage7_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage8_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage9_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage10_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp0_stage4_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state61_pp0_stage5_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state62_pp0_stage6_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state63_pp0_stage7_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state64_pp0_stage8_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state65_pp0_stage9_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state66_pp0_stage10_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state67_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ext_blocking_n = (1'b1 & 1'b1);

assign ap_int_blocking_n = (1'b1 & 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage10;

assign ap_str_blocking_n = (1'b1 & 1'b1);

assign c3_1_cast13_fu_625_p1 = select_ln17_reg_930;

assign empty_71_fu_395_p0 = empty_71_fu_395_p00;

assign empty_71_fu_395_p00 = ap_sig_allocacmp_c2;

assign empty_71_fu_395_p1 = 11'd121;

assign empty_fu_563_p0 = empty_fu_563_p00;

assign empty_fu_563_p00 = c2_reg_888;

assign empty_fu_563_p1 = 7'd11;

assign grp_fu_170_p_ce = 1'b1;

assign grp_fu_170_p_din0 = grp_fu_325_p0;

assign grp_fu_170_p_din1 = grp_fu_325_p1;

assign grp_fu_170_p_opcode = 2'd0;

assign grp_fu_174_p_ce = 1'b1;

assign grp_fu_174_p_din0 = grp_fu_330_p0;

assign grp_fu_174_p_din1 = grp_fu_330_p1;

assign grp_fu_837_p0 = grp_fu_837_p00;

assign grp_fu_837_p00 = select_ln17_fu_443_p3;

assign grp_fu_837_p1 = 8'd11;

assign grp_fu_845_p0 = grp_fu_845_p00;

assign grp_fu_845_p00 = select_ln16_1_fu_522_p3;

assign grp_fu_845_p1 = 11'd121;

assign grp_fu_845_p2 = grp_fu_845_p20;

assign grp_fu_845_p20 = add_ln20_1_fu_628_p2;

assign icmp_ln16_fu_401_p2 = ((ap_sig_allocacmp_indvar_flatten93_load == 11'd1331) ? 1'b1 : 1'b0);

assign icmp_ln17_fu_413_p2 = ((ap_sig_allocacmp_indvar_flatten56_load == 8'd121) ? 1'b1 : 1'b0);

assign icmp_ln18_fu_425_p2 = ((ap_sig_allocacmp_c3_load == 4'd11) ? 1'b1 : 1'b0);

assign mul_ln16_1_fu_544_p0 = mul_ln16_1_fu_544_p00;

assign mul_ln16_1_fu_544_p00 = select_ln16_3_fu_533_p3;

assign mul_ln16_1_fu_544_p1 = 7'd11;

assign or_ln17_fu_437_p2 = (icmp_ln17_fu_413_p2 | and_ln16_fu_431_p2);

assign p_mid152_fu_612_p0 = p_mid152_fu_612_p00;

assign p_mid152_fu_612_p00 = add_ln17_reg_940;

assign p_mid152_fu_612_p1 = 7'd11;

assign p_mid154_fu_488_p0 = p_mid154_fu_488_p00;

assign p_mid154_fu_488_p00 = add_ln17_fu_478_p2;

assign p_mid154_fu_488_p1 = 11'd121;

assign select_ln16_1_fu_522_p3 = ((icmp_ln17_reg_913[0:0] == 1'b1) ? add_ln16_11_fu_516_p2 : c1_fu_118);

assign select_ln16_3_fu_533_p3 = ((icmp_ln17_reg_913[0:0] == 1'b1) ? add_ln16_11_fu_516_p2 : c1_fu_118);

assign select_ln16_4_fu_603_p3 = ((icmp_ln17_reg_913[0:0] == 1'b1) ? 7'd0 : empty_reg_974);

assign select_ln16_5_fu_472_p3 = ((icmp_ln17_reg_913[0:0] == 1'b1) ? 11'd0 : empty_71_reg_899);

assign select_ln16_fu_466_p3 = ((icmp_ln17_reg_913[0:0] == 1'b1) ? 4'd0 : c2_reg_888);

assign select_ln17_1_fu_618_p3 = ((and_ln16_reg_923[0:0] == 1'b1) ? p_mid152_fu_612_p2 : select_ln16_4_fu_603_p3);

assign select_ln17_2_fu_494_p3 = ((and_ln16_reg_923[0:0] == 1'b1) ? p_mid154_fu_488_p2 : select_ln16_5_fu_472_p3);

assign select_ln17_3_fu_501_p3 = ((and_ln16_reg_923[0:0] == 1'b1) ? add_ln17_fu_478_p2 : select_ln16_fu_466_p3);

assign select_ln17_4_fu_783_p3 = ((icmp_ln17_reg_913[0:0] == 1'b1) ? 8'd1 : add_ln17_1_fu_778_p2);

assign select_ln17_fu_443_p3 = ((or_ln17_fu_437_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_c3_load);

assign t0_address0 = zext_ln20_fu_833_p1;

assign t0_d0 = reg_354;

assign xor_ln16_fu_419_p2 = (icmp_ln17_fu_413_p2 ^ 1'd1);

assign zext_ln16_10_fu_753_p1 = add_ln16_8_fu_748_p2;

assign zext_ln16_11_fu_795_p1 = add_ln16_9_reg_1148;

assign zext_ln16_12_fu_809_p1 = add_ln16_10_reg_1153;

assign zext_ln16_2_fu_550_p1 = mul_ln16_1_fu_544_p2;

assign zext_ln16_3_fu_579_p1 = add_ln16_1_fu_574_p2;

assign zext_ln16_4_fu_598_p1 = add_ln16_2_fu_593_p2;

assign zext_ln16_5_fu_653_p1 = add_ln16_3_fu_648_p2;

assign zext_ln16_6_fu_673_p1 = add_ln16_4_fu_668_p2;

assign zext_ln16_7_fu_693_p1 = add_ln16_5_fu_688_p2;

assign zext_ln16_8_fu_713_p1 = add_ln16_6_fu_708_p2;

assign zext_ln16_9_fu_733_p1 = add_ln16_7_fu_728_p2;

assign zext_ln20_fu_833_p1 = add_ln20_reg_1043_pp0_iter5_reg;

assign zext_ln23_10_fu_818_p1 = add_ln23_9_fu_813_p2;

assign zext_ln23_11_fu_828_p1 = add_ln23_10_fu_823_p2;

assign zext_ln23_1_fu_584_p1 = grp_fu_837_p3;

assign zext_ln23_2_fu_643_p1 = add_ln23_1_fu_638_p2;

assign zext_ln23_3_fu_663_p1 = add_ln23_2_fu_658_p2;

assign zext_ln23_4_fu_683_p1 = add_ln23_3_fu_678_p2;

assign zext_ln23_5_fu_703_p1 = add_ln23_4_fu_698_p2;

assign zext_ln23_6_fu_723_p1 = add_ln23_5_fu_718_p2;

assign zext_ln23_7_fu_743_p1 = add_ln23_6_fu_738_p2;

assign zext_ln23_8_fu_773_p1 = add_ln23_7_fu_768_p2;

assign zext_ln23_9_fu_804_p1 = add_ln23_8_fu_799_p2;

endmodule //krnl_helm_compute_1_Pipeline_VITIS_LOOP_16_5_VITIS_LOOP_17_6_VITIS_LOOP_18_7
